import type { HomeContent } from "./types";

export const profileEn = {
  locale: "en",
  draftMode: false,
  seo: { title: "Tianyuan Nie | Projects, Research, Notes", description: "Selected projects, ongoing research, and notes by Tianyuan Nie." },
  name: "Tianyuan Nie", romanizedName: "聂田塬", initials: "NTY", eyebrow: "Selected Work · 2023—Now",
  headlineLines: ["Projects, research,", "and notes."],
  introduction: "A collection of selected work, ongoing research, and notes along the way.",
  about: "I enjoy turning complex requirements into testable decisions and research ideas into working prototypes. In engineering, I care about clear service boundaries, dependable data flows, and observability. In research, I explore the intersection of cryptography, artificial intelligence, and passive IoT.",
  facts: [{ label: "Location", value: "China · UTC+8" }, { label: "Education", value: "HUST · Cryptography Science and Technology" }, { label: "Principle", value: "Evidence over assumptions" }],
  availability: "Trilingual edition in review",
  focusAreas: [
    { index: "01", title: "Backend Systems", description: "Designing clear APIs, maintainable services, and dependable data flows for complex products.", tags: ["Go", "API Design", "Service Engineering"] },
    { index: "02", title: "Trustworthy AI & Privacy", description: "Exploring secure training and inference through MPC, zero-knowledge proofs, and privacy-preserving machine learning.", tags: ["MPC", "Zero-Knowledge", "Privacy ML"] },
    { index: "03", title: "Software Security", description: "Using program analysis, code slicing, and fuzzing to understand vulnerabilities and build practical security tools.", tags: ["Static Analysis", "Code Security", "Fuzzing"] },
    { index: "04", title: "Intelligent Edge Systems", description: "Combining signal processing, machine learning, and FPGA implementation for low-power sensing and communication systems.", tags: ["Backscatter", "Signal Processing", "FPGA"] },
  ],
  education: [{ id: "hust", kicker: "Undergraduate", title: "Huazhong University of Science and Technology", subtitle: "School of Cyber Science and Engineering · Cryptography Science and Technology", period: "Sep 2023 — Present", summary: "Studying cryptographic theory and software/hardware implementation, mathematical foundations, and applied artificial intelligence. Weighted average: 90.45/100; comprehensive ranking: 1st of 45.", highlights: ["Weighted average: 90.45 / 100; ranked 1st of 45 in the program’s comprehensive evaluation", "Coursework in principles of cryptography, cryptographic hardware engineering, and cryptographic software practice", "Mathematical foundations of cryptography and applied AI with Python"], tags: ["Cryptography", "Cybersecurity", "Artificial Intelligence"] }],
  experience: [{ id: "bytedance", kicker: "Engineering", title: "ByteDance", subtitle: "China Commerce & Ads · Backend Engineering Intern", period: "Apr 2026 — Present", summary: "Contributing to backend systems for merchant–creator collaboration products in local services.", highlights: ["Deliver backend features from requirement analysis and design through implementation and rollout", "Work with MySQL, Redis, and Kafka while improving service performance and reliability", "Contribute to code-grounded knowledge and observability capabilities that make complex flows easier to understand and diagnose"], tags: ["Backend Engineering", "Go", "MySQL", "Redis", "Kafka"] }],
  projects: [
    { id: "privacy-ai", kicker: "Ongoing research", title: "Privacy-Preserving AI and Trusted Computing", subtitle: "Research Member", period: "Nov 2025 — Present", status: "Ongoing", summary: "Researching privacy-preserving training and secure inference by combining large language models with modern cryptography.", highlights: ["Explore MPC for protected model training and fine-tuning", "Investigate watermarking for agentic AI workflows and verifiable AI with zero-knowledge proofs"], tags: ["LLM", "MPC", "Zero-Knowledge", "Trusted AI"] },
    { id: "llm-supply-chain", kicker: "Paper · Software Engineering", title: "Large-Language-Model Supply Chain Security", subtitle: "Third Author", period: "Mar 2025 — May 2025", status: "Internetware 2026", summary: "An empirical study of 13,486 open-source packages and 180 vulnerabilities, examining the structure, functional domains, and risk propagation of the LLM supply chain.", highlights: ["Built a supply-chain graph with 28,704 dependency edges and characterized core dependencies and recurring topologies", "Quantified cascading vulnerability impact across dependency layers; accepted by Internetware 2026"], tags: ["AI Security", "Software Supply Chain", "Empirical Study"], media: { src: "/images/research/llm-supply-chain-paper-page.webp", alt: "First page of the large-language-model supply-chain paper, showing its title, authors, abstract, and opening text", caption: "Paper first page · arXiv:2504.20763v2. Rendered proportionally from the original PDF without cropping or overlays.", source: { label: "arXiv · PDF", href: "https://arxiv.org/pdf/2504.20763v2" } }, links: [{ label: "Abstract", href: "https://arxiv.org/abs/2504.20763" }, { label: "HTML", href: "https://arxiv.org/html/2504.20763v2" }, { label: "PDF", href: "https://arxiv.org/pdf/2504.20763v2" }] },
    { id: "secure-backscatter", kicker: "Research project", title: "Secure Backscatter Transmission with Chaotic Sequences", subtitle: "Project Lead", period: "Mar 2025 — Mar 2026", status: "Completed", summary: "Designed and implemented a lightweight secure coding method for passive-IoT backscatter communication.", highlights: ["Developed a chaotic-sequence differential modulation scheme", "Improved endpoint energy efficiency and resistance to man-in-the-middle attacks without reducing throughput", "Selected for a provincial undergraduate innovation program"], tags: ["Backscatter", "Secure Communication", "Passive IoT"] },
    { id: "signal-recognition", kicker: "Journal Paper · Intelligent Hardware", title: "Intelligent Signal Recognition for Passive IoT", subtitle: "First Author", period: "Mar 2025 — Mar 2026", status: "Published · 2026", summary: "Proposed a single-frequency metamaterial passive-IoT sensing framework and a model-driven deep network for end-to-end recognition of reflection parameters and environmental quantities.", highlights: ["Led channel-estimation and intelligent-recognition algorithm design, numerical evaluation, and embedded FPGA validation", "Published in Complex & Intelligent Systems; DOI: 10.1007/s40747-026-02240-4"], tags: ["Signal Recognition", "Deep Learning", "Metamaterial", "Passive IoT"], media: { src: "/images/research/signal-recognition-paper-page.webp", alt: "First page of the passive-IoT signal-recognition paper, showing the journal, title, authors, abstract, and keywords", caption: "Paper first page · Complex & Intelligent Systems 12:126 (2026). Rendered proportionally from the open-access PDF without cropping or overlays.", source: { label: "Springer · Article", href: "https://link.springer.com/article/10.1007/s40747-026-02240-4" }, license: { label: "CC BY-NC-ND 4.0", href: "https://creativecommons.org/licenses/by-nc-nd/4.0/" } }, links: [{ label: "DOI", href: "https://doi.org/10.1007/s40747-026-02240-4" }, { label: "Open article", href: "https://link.springer.com/article/10.1007/s40747-026-02240-4" }, { label: "PDF", href: "https://link.springer.com/content/pdf/10.1007/s40747-026-02240-4.pdf" }] },
  ],
  awards: [
    { year: "2025", title: "China Cryptography Technology Competition", award: "National Second Prize", description: "Led a three-person team building an LLM-assisted prototype for detecting cryptographic API misuse." },
    { year: "2025", title: "National Undergraduate Embedded Chip and System Design Competition", award: "National Third Prize", description: "Developed algorithms and FPGA deployment for a passive-IoT monitoring system." },
    { year: "2025", title: "China Software Cup", award: "National Third Prize", description: "Contributed product design and frontend development to an AI-assisted interview application." },
    { year: "2024–2025", title: "Mathematics & Modeling Competitions", award: "Two Hubei First Prizes", description: "First prizes in the National College Mathematics Competition and the Contemporary Undergraduate Mathematical Contest in Modeling, Hubei division." },
  ],
  exchange: { id: "hokudai", kicker: "International experience", title: "Hokkaido University", subtitle: "Hokudai Summer Institute", period: "Aug 2024", summary: "Completed an English-taught summer program in sustainable tourism and economics, including a final presentation.", highlights: ["Final grade: A−"], tags: ["Hokkaido University", "Summer Institute", "English-taught Program"] },
  skills: [
    { title: "Programming & Backend", items: ["Go", "C / C++", "Python", "TypeScript", "JavaScript", "MySQL", "Redis", "Kafka"] },
    { title: "Frontend", items: ["React", "Vue 3", "Redux", "Vite", "Webpack", "Tailwind CSS"] },
    { title: "Security & Program Analysis", items: ["Web Security", "Tree-sitter", "AST", "CFG / DFG", "Fuzzing", "Wireshark"] },
    { title: "AI & Privacy", items: ["PyTorch", "scikit-learn", "LangChain", "LLM Agents", "MPC", "Zero-Knowledge", "CrypTen"] },
    { title: "Communication & Hardware", items: ["MIMO / OFDM", "Backscatter", "Signal Processing", "MATLAB / Simulink", "FPGA / Verilog"] },
    { title: "Tools & Languages", items: ["Git / GitHub", "Linux", "Docker", "GitHub Actions", "Mandarin Chinese", "English (CET-4 / CET-6)"] },
  ],
  contact: { heading: "Let’s discuss engineering, research, and useful ideas.", body: "I welcome conversations about backend engineering, AI security, privacy-preserving computation, and intelligent systems.", links: [{ label: "Email", href: "mailto:tianyuannie@hust.edu.cn" }, { label: "GitHub", href: "https://github.com/Misat0N" }] },
  missingContent: ["Upload a personal portrait for the homepage", "Complete the final review of the Chinese, English, and Japanese copy", "Confirm the production domain and review the deployed site"],
  ui: { draftLabel: "Draft 02", draftText: "Trilingual copy draft. Publication boundaries and translations still require review.", navLabel: "Primary navigation", homeLabel: "Home", nav: { about: "About", focus: "Focus", resume: "Resume", work: "Work", contact: "Contact" }, greeting: "Hello, I’m", viewWork: "View selected work", contactCta: "Contact", highlights: "Highlights", tagsLabel: "Technical tags", currentStatus: "Status", backToTop: "Back to top", themeToLight: "Switch to light theme", themeToDark: "Switch to dark theme", sections: {
    about: { index: "01", eyebrow: "About", title: "Understand first. Design second.", description: "Engineering and research both begin with explicit assumptions." }, focus: { index: "02", eyebrow: "Focus", title: "What I care about.", description: "From backend systems to trustworthy intelligence, clarity at every layer." }, education: { index: "03", eyebrow: "Education", title: "Learning and foundations." }, experience: { index: "04", eyebrow: "Experience", title: "Engineering practice." }, work: { index: "05", eyebrow: "Research & Projects", title: "Selected work." }, awards: { index: "06", eyebrow: "Awards", title: "Competitions and recognition." }, skills: { index: "07", eyebrow: "Skills", title: "Tools and capabilities." }, exchange: { index: "08", eyebrow: "International", title: "International experience." }, contact: { index: "09", eyebrow: "Contact", title: "Stay in touch." }, materials: { index: "10", eyebrow: "Review", title: "Before publishing.", description: "These details will remain private until confirmed." },
  } },
} satisfies HomeContent;
