import type { HomeContent } from "./types";

export const profileZh = {
  locale: "zh",
  draftMode: false,
  seo: {
    title: "聂田塬｜项目、研究与随记",
    description: "聂田塬的个人主页：做过的项目、进行中的研究，以及沿途记录。",
  },
  name: "聂田塬",
  romanizedName: "Tianyuan Nie",
  initials: "NTY",
  eyebrow: "Selected Work · 2023—Now",
  headlineLines: ["项目、研究，", "以及一些随记。"],
  introduction: "这里收录做过的项目、进行中的研究，以及沿途留下的记录。",
  about: "我喜欢把复杂需求拆成可验证的判断，把研究想法做成可以运行的原型。工程实践中，我关注清晰的服务边界、稳定的数据流与可观测性；研究中，我探索密码学、人工智能与无源物联网的交叉问题。",
  facts: [
    { label: "Location", value: "中国 · UTC+8" },
    { label: "Education", value: "华中科技大学 · 密码科学与技术" },
    { label: "Principle", value: "Evidence over assumptions" },
  ],
  availability: "三语版本整理中",
  focusAreas: [
    { index: "01", title: "后端系统", description: "设计清晰的 API、可维护的服务与可靠的数据流，支撑复杂业务长期演进。", tags: ["Go", "API Design", "Service Engineering"] },
    { index: "02", title: "可信 AI 与隐私", description: "探索 MPC、零知识证明和隐私保护机器学习在安全训练与推理中的应用。", tags: ["MPC", "Zero-Knowledge", "Privacy ML"] },
    { index: "03", title: "软件安全", description: "使用程序分析、代码切片与 Fuzz 等方法理解漏洞并构建实用安全工具。", tags: ["Static Analysis", "Code Security", "Fuzzing"] },
    { index: "04", title: "智能边缘系统", description: "结合信号处理、机器学习与 FPGA 实现低功耗感知和通信系统。", tags: ["Backscatter", "Signal Processing", "FPGA"] },
  ],
  education: [{
    id: "hust", kicker: "本科教育", title: "华中科技大学", subtitle: "网络空间安全学院 · 密码科学与技术", period: "2023.09 — 至今",
    summary: "学习密码理论、密码软硬件、数学基础与人工智能实践。加权成绩 90.45，专业综合评价 1 / 45。",
    highlights: ["加权成绩 90.45 / 100；专业综合评价排名 1 / 45", "主修密码学原理、密码硬件工程基础、密码软件综合实践", "学习密码学数学基础与 Python 人工智能实践"],
    tags: ["Cryptography", "Cybersecurity", "Artificial Intelligence"],
  }],
  experience: [{
    id: "bytedance", kicker: "工程实践", title: "字节跳动", subtitle: "中国交易与广告 · 后端开发实习生", period: "2026.04 — 至今",
    summary: "参与生活服务场景中商家与创作者协作业务的后端系统建设。",
    highlights: ["从需求分析、方案设计到后端实现与上线交付，完成复杂业务功能开发", "参与服务性能与稳定性优化，使用 MySQL、Redis、Kafka 等基础组件", "参与代码知识体系与可观测能力建设，提升复杂链路的理解和故障定位效率"],
    tags: ["Backend Engineering", "Go", "MySQL", "Redis", "Kafka"],
  }],
  projects: [
    { id: "privacy-ai", kicker: "研究中", title: "隐私保护 AI 与可信计算", subtitle: "研究成员", period: "2025.11 — 至今", status: "Ongoing", summary: "研究大语言模型与现代密码技术结合的隐私保护训练和安全推理。", highlights: ["探索 MPC 密态模型训练与微调", "研究 Agentic AI 链路水印与基于零知识证明的可验证 AI"], tags: ["LLM", "MPC", "Zero-Knowledge", "Trusted AI"] },
    { id: "llm-supply-chain", kicker: "论文 · 软件工程", title: "大语言模型供应链安全", subtitle: "第三作者", period: "2025.03 — 2025.05", status: "Internetware 2026", summary: "对 13,486 个开源包与 180 个漏洞开展实证研究，分析大语言模型供应链的结构、功能域与风险传播。", highlights: ["构建包含 28,704 条依赖边的供应链图谱，刻画核心依赖与典型拓扑", "量化漏洞沿依赖链的级联影响；论文已被 Internetware 2026 接收"], tags: ["AI Security", "Software Supply Chain", "Empirical Study"], media: { src: "/images/research/llm-supply-chain-paper-page.webp", alt: "大语言模型供应链论文首页，展示标题、作者、摘要与论文正文开头", caption: "论文首页 · arXiv:2504.20763v2。由原始 PDF 第一页等比缩放生成，未裁切、未叠字。", source: { label: "arXiv · PDF", href: "https://arxiv.org/pdf/2504.20763v2" } }, links: [{ label: "论文摘要", href: "https://arxiv.org/abs/2504.20763" }, { label: "HTML 全文", href: "https://arxiv.org/html/2504.20763v2" }, { label: "PDF", href: "https://arxiv.org/pdf/2504.20763v2" }] },
    { id: "secure-backscatter", kicker: "项目研究", title: "基于混沌序列的背向散射安全传输", subtitle: "项目负责人", period: "2025.03 — 2026.03", status: "Completed", summary: "面向无源物联网设计轻量化安全编码方案，并完成系统实现与实验验证。", highlights: ["提出基于混沌序列差分调制的安全编码方法", "在保持吞吐能力的同时改善端侧能耗与中间人攻击抵抗能力", "项目获推荐为省级大学生创新创业训练计划项目"], tags: ["Backscatter", "Secure Communication", "Passive IoT"] },
    { id: "signal-recognition", kicker: "期刊论文 · 智能硬件", title: "无源物联网信号智能识别", subtitle: "第一作者", period: "2025.03 — 2026.03", status: "Published · 2026", summary: "提出单频点超材料无源物联网感知框架，并以模型驱动的深度网络完成反射参数与环境物理量的端到端识别。", highlights: ["负责信道估计与智能信号识别算法设计，完成数值实验与 FPGA 部署验证", "发表于 Complex & Intelligent Systems，DOI: 10.1007/s40747-026-02240-4"], tags: ["Signal Recognition", "Deep Learning", "Metamaterial", "Passive IoT"], media: { src: "/images/research/signal-recognition-paper-page.webp", alt: "无源物联网信号智能识别论文首页，展示期刊、标题、作者、摘要与关键词", caption: "论文首页 · Complex & Intelligent Systems 12:126 (2026)。由开放获取 PDF 第一页等比缩放生成，未裁切、未叠字。", source: { label: "Springer · Article", href: "https://link.springer.com/article/10.1007/s40747-026-02240-4" }, license: { label: "CC BY-NC-ND 4.0", href: "https://creativecommons.org/licenses/by-nc-nd/4.0/" } }, links: [{ label: "DOI", href: "https://doi.org/10.1007/s40747-026-02240-4" }, { label: "开放全文", href: "https://link.springer.com/article/10.1007/s40747-026-02240-4" }, { label: "PDF", href: "https://link.springer.com/content/pdf/10.1007/s40747-026-02240-4.pdf" }] },
  ],
  awards: [
    { year: "2025", title: "全国密码技术竞赛", award: "国家二等奖", description: "担任队长，完成基于大模型的密码 API 误用检测原型。" },
    { year: "2025", title: "全国大学生嵌入式芯片与系统设计竞赛", award: "国家三等奖", description: "负责无源物联网监测系统的算法设计与 FPGA 部署。" },
    { year: "2025", title: "中国软件杯大学生软件设计大赛", award: "国家三等奖", description: "参与 AI 面试助手的功能设计与前端实现。" },
    { year: "2024–2025", title: "数学与建模竞赛", award: "湖北省一等奖 × 2", description: "全国大学生数学竞赛与全国大学生数学建模竞赛湖北赛区一等奖。" },
  ],
  exchange: { id: "hokudai", kicker: "海外交流", title: "北海道大学", subtitle: "Hokudai Summer Institute", period: "2024.08", summary: "完成可持续旅游与经济学方向的全英文课程学习与结题答辩。", highlights: ["课程成绩 A−"], tags: ["Hokkaido University", "Summer Institute", "English-taught Program"] },
  skills: [
    { title: "编程与后端", items: ["Go", "C / C++", "Python", "TypeScript", "JavaScript", "MySQL", "Redis", "Kafka"] },
    { title: "前端与全栈", items: ["React", "Vue 3", "Redux", "Vite", "Webpack", "Tailwind CSS"] },
    { title: "安全与代码分析", items: ["Web Security", "Tree-sitter", "AST", "CFG / DFG", "Fuzzing", "Wireshark"] },
    { title: "AI 与隐私", items: ["PyTorch", "scikit-learn", "LangChain", "LLM Agents", "MPC", "Zero-Knowledge", "CrypTen"] },
    { title: "通信与硬件", items: ["MIMO / OFDM", "Backscatter", "Signal Processing", "MATLAB / Simulink", "FPGA / Verilog"] },
    { title: "工程工具与语言", items: ["Git / GitHub", "Linux", "Docker", "GitHub Actions", "中文（普通话二甲）", "英语（CET-4 / CET-6）"] },
  ],
  contact: { heading: "聊聊工程、研究与长期有价值的事。", body: "欢迎就后端工程、AI 安全、隐私计算与智能系统交流。", links: [{ label: "Email", href: "mailto:tianyuannie@hust.edu.cn" }, { label: "GitHub", href: "https://github.com/Misat0N" }] },
  missingContent: ["上传用于主页的个人照片", "最终审阅中英日三种文案", "确认正式域名和部署后的访问效果"],
  ui: {
    draftLabel: "Draft 02", draftText: "三语内容草稿，公开边界与翻译尚待本人确认。", navLabel: "主导航", homeLabel: "首页", nav: { about: "关于", focus: "关注", resume: "经历", work: "项目", contact: "联系" }, greeting: "你好，我是", viewWork: "查看项目", contactCta: "联系我", highlights: "要点", tagsLabel: "技术标签", currentStatus: "当前状态", backToTop: "回到顶部", themeToLight: "切换到浅色模式", themeToDark: "切换到深色模式",
    sections: {
      about: { index: "01", eyebrow: "About", title: "先理解问题，再设计答案。", description: "工程与研究，都从明确前提开始。" },
      focus: { index: "02", eyebrow: "Focus", title: "关注的事情。", description: "从服务端到可信智能，把每一层做清楚。" },
      education: { index: "03", eyebrow: "Education", title: "学习与基础。" },
      experience: { index: "04", eyebrow: "Experience", title: "工程实践。" },
      work: { index: "05", eyebrow: "Research & Projects", title: "研究与项目。" },
      awards: { index: "06", eyebrow: "Awards", title: "竞赛与荣誉。" },
      skills: { index: "07", eyebrow: "Skills", title: "工具与能力。" },
      exchange: { index: "08", eyebrow: "International", title: "海外交流。" },
      contact: { index: "09", eyebrow: "Contact", title: "保持联系。" },
      materials: { index: "10", eyebrow: "Review", title: "发布前需要确认。", description: "这些信息不会在确认前正式公开。" },
    },
  },
} satisfies HomeContent;
